### ISSUE TITLE
issue: Timeout failure on restart

### ISSUE THREAD

**Issue by tyler36** [JanoPL/ddev-kibana#1]
Thanks for making the addon. 

I've started learning elasticsearch for Drupal and thought I would try this addon too.
I have ElasticSearch in Drupal via the official addon for DDEV.

I tried to add this addon too with the following command: `ddev get janopl/ddev-kibana`

However, when I restart DDEV, I get the following error:

```shell
Failed to start elasticsearch-d94-demo: container(s) failed to become healthy before their configured timeout or in 120 seconds. This may be just a problem with the healthcheck and not a functional problem. (container /ddev-elasticsearch-d94-demo-kibana is unhealthy: ) 
```

When I run `ddev logs -s kibana`, I

```shell
...
{"type":"log","@timestamp":"2022-09-28T03:27:26+00:00","tags":["info","status"],"pid":7,"message":"Kibana is now available (was degraded)"}
{"type":"log","@timestamp":"2022-09-28T03:27:29+00:00","tags":["info","plugins","reporting","chromium"],"pid":7,"message":"Browser executable: /usr/share/kibana/x-pack/plugins/reporting/chromium/headless_shell-linux_x64/headless_shell"}agent":"curl/7.68.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"curl/7.68.0"},"res":{"statusCode":302,"responseTime":6},"message":"GET / 302 6ms"}
...
```

The last message appears about 20-30 times or so. I'm not familiar with kibana so I'm not sure if this is expected behavior or not.

**Comment by JanoPL** [comment]
Hi 

Sometimes kibana container has some issue with healthcheck parameter in docker compose file

you can also check if kibana is boot up correctly to check kibana api status.

first you need comment or remove healthcheck section in docker-compose.kibana.yaml and boot up your project 

there is an address to check the kibana status ``` http://<your-project-name>.ddev.site:5601/api/status ```

it should return status for all plugins and kibana herself and should be something like "state": "green" especially in "overall" section in response body

you can increase healthcheck values for interval and timeout in file "docker-compose.kibana.yaml" and check if this resolve your issue

from:
```
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail -s localhost:5601" ]
      interval: 30s
      timeout: 10s
      retries: 3
```
to: 
```
 healthcheck:
      test: [ "CMD-SHELL", "curl --fail -s localhost:5601" ]
      interval: 60s
      timeout: 30s
      retries: 3
```

if this doesn't help, you can modify healthcheck test to 
```
    healthcheck:
      test: [ "CMD-SHELL", "curl  --fail -s \"http://localhost:5601/api/status\" | grep 'Looking good'" ]
      interval: 60s
      timeout: 30s
      retries: 3
```

after start project you should have in kibana container logs something similar to this 
```
{"type":"response","@timestamp":"2022-09-28T14:27:27+00:00","tags":["api"],"pid":7,"method":"get","statusCode":200,"req":{"url":"/api/status","method":"get","headers":{"host":"localhost:5601","user-agent":"curl/7.68.0","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"curl/7.68.0"},"res":{"statusCode":200,"responseTime":4,"contentLength":24697},"message":"GET /api/status 200 4ms - 24.1KB"}
```

Let me know if the above suggestions help you then I will make changes to the repo.
